/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import scene from '../../public/assets/3D/keycaps.glb'


const KeyCaps = ({...props}) => {
    const { nodes, materials } = useGLTF(scene)
    return (
        <group {...props} dispose={null}>
            <group>
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Plane.geometry}
                    material={materials.SpecialKeyCapsMaterial}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Plane_1.geometry}
                    material={materials.LetteringMaterial}
                />
            </group>
            <group>
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Plane124.geometry}
                    material={materials.SpecialKeysMaterial}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Plane124_1.geometry}
                    material={materials.BaseKeyCapMaterial}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Plane124_2.geometry}
                    material={materials.LetteringMaterial}
                />
            </group>
        </group>
    )
}

export default KeyCaps;