/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, {useEffect, useRef} from 'react'
import { useGLTF } from '@react-three/drei'
import scene from '../../public/assets/3D/keycaps.glb'
import gsap from "gsap";
import {useGSAP} from "@gsap/react";


const KeyCaps = ({currentKeyCap, toAnimate, isCollapsed, ...props}) => {

    useEffect(() => {
        materials["BaseKeyCapMaterial"].color.set(currentKeyCap.base);
        materials["SpecialKeysMaterial"].color.set(currentKeyCap.special);
        materials["LetteringMaterial"].color.set("#000000");
    }, [currentKeyCap]);

    const CapsRef = useRef();

    useGSAP(() => {
        if(!CapsRef.current) return;
        gsap.fromTo(CapsRef.current.position,  {y: 0.5}, {y: 0.2, duration: 0.5, ease: "easeOut"});
    }, [toAnimate]);

    useGSAP(() => {
        if(!CapsRef.current) return;
        gsap.fromTo(CapsRef.current.position,  {y: 0.2}, {y: 0.03, duration: 1, ease: "easeOut"});
    }, [isCollapsed]);

    const { nodes, materials } = useGLTF(scene)
    return (
        <group ref={CapsRef} {...props} dispose={null}>
            <group position={[0, 0.006, 0.001]}>
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Plane.geometry}
                    material={materials.LetteringMaterial}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Plane_1.geometry}
                    material={materials.LetteringMaterial}
                />
            </group>
            <group>
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Plane124.geometry}
                    material={materials.SpecialKeysMaterial}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Plane124_1.geometry}
                    material={materials.BaseKeyCapMaterial}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Plane124_2.geometry}
                    material={materials.LetteringMaterial}
                />
            </group>
        </group>
    )
}

export default KeyCaps;