/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import scene from '../../public/assets/3D/PCB.glb'

const PCB = ({...props}) => {
    const { nodes, materials } = useGLTF(scene)
    return (
        <group {...props} dispose={null}>
            <group position={[0, 0.001, 0]}>
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Plane123.geometry}
                    material={materials.PCBMaterial}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Plane123_1.geometry}
                    material={materials.GoldPinConnector}
                />
            </group>
        </group>
    )
}

export default PCB;