/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, {useEffect, useRef} from 'react'
import { useGLTF } from '@react-three/drei'
import scene from '../../public/assets/3D/plate.glb'


const Plate = ({currentPlate, ...props}) => {

    const { nodes, materials } = useGLTF(scene)

    useEffect(() => {
        materials["PlateMaterial"].color.set(currentPlate.color);
    }, [currentPlate]);

    return (
        <group {...props} dispose={null}>
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Plate.geometry}
                material={materials.PlateMaterial}
                position={[0, 0.001, 0]}
            />
        </group>
    )
}

export default Plate;

