/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import scene from '../../public/assets/3D/plate.glb'


const Plate = ({...props}) => {
    const { nodes, materials } = useGLTF(scene)
    return (
        <group {...props} dispose={null}>
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Plate.geometry}
                material={materials.PlateMaterial}
                position={[0, 0.001, 0]}
            />
        </group>
    )
}

export default Plate;

