/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import scene from '../../public/assets/3D/switches.glb'

const Switches =({...props}) => {
    const { nodes, materials } = useGLTF(scene)
    return (
        <group {...props} dispose={null}>
            <group>
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Plane116.geometry}
                    material={materials['Black Plastic']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Plane116_1.geometry}
                    material={materials.GoldPinConnector}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Plane116_2.geometry}
                    material={materials['Red Plastic']}
                />
            </group>
        </group>
    )
}

export default Switches;